commerce_checkout.commerce_checkout_pane.custom_checkout_message:
  type: commerce_checkout_pane_configuration
  mapping:
    message:
      type: text_format
      label: 'Custom Checkout Message'
      translatable: true
