prlp.settings:
  type: config_object
  label: 'PRLP module settings'
  mapping:
    password_required:
      type: integer
      label: 'Password Required'
    login_destination:
      type: label
      label: 'Login Destination'
