field.widget.third_party.media_library_edit:
  type: mapping
  label: 'Media library edit settings'
  mapping:
    show_edit:
      type: boolean
      label: 'Show edit button'
    edit_form_mode:
      type: string
      label: 'Edit form mode'
